### ISSUE TITLE
Phone Earpiece not working after clean flash

### ISSUE THREAD

**Issue by daunikman** [UMIDIGI-MT6763-Development/android_device_umidigi_breeze#2]
I installed this from Stock rom as explained on your page
After install

1. Phone earpiece does not work, speaker and earphone works but phone earpiece does not work.
2. Switching from LTE to WCDMA and back makes the phone to lose Mobile Data until reboot.
3. Call volume cannot be controlled

**What I did:**

- Unlocked boot loader using fastboot
- Flashed your latest TWRP
- boot into TWRP
- Did an Advance Wipe - System and Cache
- Install from Zip - Lineage 17.1, Nikapp Basics, Magisks. 
- Clear Dalvik Cache
- Reboot.

When I rebooted, media keeps stoping appears, clear download cache, force closed, and reboot.

**Comment by Hadenix** [comment]
strange I didn’t even have this. try to write in telegram chat, the answer will come faster
